version: '{build}'

os: Visual Studio 2015

before_build:
- nuget restore

build:
  publish_wap: true
  verbosity: minimal
  project: src\Wuzlstats\project.json    

configuration: Release

deploy:
- provider: WebDeploy
  server: http://wuzlstats.sachsenhofer.com/MSDEPLOYAGENTSERVICE
  website: Wuzlstats
  username: Administrator
  password:
    secure: 0VezCAl9nnPtt2Kdqabh3Q==
  ntlm: true
  remove_files: true
  app_offline: false
  aspnet5: true
  on:
    branch: master
