version: '{build}'

os: Visual Studio 2015

branches:
  only:
    - master

build_script:
- cd ./src/Wuzlstats
- CALL dotnet restore
- CALL dotnet publish --configuration Release --output bin/publish

artifacts:
- path: ./src/Wuzlstats/bin/publish
  name: Web application

environment:
  deploy_server:
    secure: 7f9bcFkXgx37td51cnPI9A==
  deploy_username:
    secure: +4+0JDINyo6SMCl7QDFxjA==
  deploy_password:
    secure: RHmwJ0TuDaknqQdBiIUtYiO6NSmxqEbXDACMtJG16W4=


deploy_script:
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:recycleApp -dest:recycleApp=Wuzlstats,recycleMode=StopAppPool,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPath=%APPVEYOR_BUILD_FOLDER%\src\Wuzlstats\bin\publish -dest:contentPath=Wuzlstats,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%
- CALL "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:recycleApp -dest:recycleApp=Wuzlstats,recycleMode=StartAppPool,computername=http://%deploy_server%/MSDEPLOYAGENTSERVICE,username=%deploy_username%,password=%deploy_password%