version: '{build}'

os: Visual Studio 2015

install:
 - cmd: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
 - cmd: nuget sources add -Name AspNetVNext -Source https://www.myget.org/F/aspnetvnext/api/v2

before_build:
 - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
 - ps: dnvm install 1.0.0-beta6
 - ps: dnvm use 1.0.0-beta6
 - ps: dnu restore --quiet
 - ps: nuget restore
 - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

build:
  publish_wap: true
  verbosity: minimal

configuration: Release

deploy:
- provider: WebDeploy
  server: http://wuzlstats.sachsenhofer.com/MSDEPLOYAGENTSERVICE
  website: Wuzlstats
  username: Administrator
  password:
    secure: 0VezCAl9nnPtt2Kdqabh3Q==
  ntlm: true
  remove_files: true
  app_offline: false
  aspnet5: true
  on:
    branch: master
