version: '{build}'

os: Visual Studio 2015

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm --prefix .\src\Wuzlstats install .\src\Wuzlstats
  - dnvm install -arch x64 1.0.0-beta8
  - dnvm install -arch x86 1.0.0-beta8
  - dnvm use 1.0.0-beta8 --arch x86

build_script:
  - SET PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - CALL dnu publish ".\src\Wuzlstats" --out "%~dp0artifacts\publish" --configuration Release --no-source --runtime dnx-clr-win-x64.1.0.0-beta8 --wwwroot-out "wwwroot" --quiet

artifacts:
- path: artifacts/publish

deploy:
- provider: WebDeploy
  server: http://85.93.17.211/MSDEPLOYAGENTSERVICE
  website: Wuzlstats
  username: Administrator
  password:
    secure: 0VezCAl9nnPtt2Kdqabh3Q==
  ntlm: true
  remove_files: true
  app_offline: false
  aspnet5: true
  on:
    branch: master
